import { defineField, defineType } from 'sanity';
import { DownloadIcon } from '@sanity/icons';

export const brochureDownload = defineType({
  name: 'brochureDownload',
  title: 'Brochure Download',
  type: 'document',
  icon: DownloadIcon,
  // Note: Table view configuration is handled by the table plugin
  // The table plugin will automatically detect and display document fields
  fields: [
    defineField({
      name: 'fullName',
      title: 'Full Name',
      type: 'string',
      validation: (Rule) => Rule.required().max(100),
      description: 'Full name of the person downloading the brochure',
    }),
    defineField({
      name: 'email',
      title: 'Email Address',
      type: 'string',
      validation: (Rule) => 
        Rule.required()
          .email()
          .error('Please enter a valid email address'),
      description: 'Email address for contact and follow-up',
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      validation: (Rule) => Rule.required().max(20),
      description: 'Contact phone number',
    }),
    defineField({
      name: 'organization',
      title: 'Organization/Institution',
      type: 'string',
      validation: (Rule) => Rule.max(150),
      description: 'Organization or institution name (optional)',
    }),
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
      validation: (Rule) => Rule.required(),
      description: 'Country of residence',
      options: {
        list: [
          // Major countries first (most commonly selected)
          { title: 'United States', value: 'United States' },
          { title: 'United Kingdom', value: 'United Kingdom' },
          { title: 'Canada', value: 'Canada' },
          { title: 'Australia', value: 'Australia' },
          { title: 'Germany', value: 'Germany' },
          { title: 'France', value: 'France' },
          { title: 'India', value: 'India' },
          { title: 'China', value: 'China' },
          { title: 'Japan', value: 'Japan' },
          { title: 'Brazil', value: 'Brazil' },

          // All other countries alphabetically
          { title: 'Afghanistan', value: 'Afghanistan' },
          { title: 'Albania', value: 'Albania' },
          { title: 'Algeria', value: 'Algeria' },
          { title: 'Andorra', value: 'Andorra' },
          { title: 'Angola', value: 'Angola' },
          { title: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
          { title: 'Argentina', value: 'Argentina' },
          { title: 'Armenia', value: 'Armenia' },
          { title: 'Austria', value: 'Austria' },
          { title: 'Azerbaijan', value: 'Azerbaijan' },
          { title: 'Bahamas', value: 'Bahamas' },
          { title: 'Bahrain', value: 'Bahrain' },
          { title: 'Bangladesh', value: 'Bangladesh' },
          { title: 'Barbados', value: 'Barbados' },
          { title: 'Belarus', value: 'Belarus' },
          { title: 'Belgium', value: 'Belgium' },
          { title: 'Belize', value: 'Belize' },
          { title: 'Benin', value: 'Benin' },
          { title: 'Bhutan', value: 'Bhutan' },
          { title: 'Bolivia', value: 'Bolivia' },
          { title: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
          { title: 'Botswana', value: 'Botswana' },
          { title: 'Brunei', value: 'Brunei' },
          { title: 'Bulgaria', value: 'Bulgaria' },
          { title: 'Burkina Faso', value: 'Burkina Faso' },
          { title: 'Burundi', value: 'Burundi' },
          { title: 'Cape Verde', value: 'Cape Verde' },
          { title: 'Cambodia', value: 'Cambodia' },
          { title: 'Cameroon', value: 'Cameroon' },
          { title: 'Central African Republic', value: 'Central African Republic' },
          { title: 'Chad', value: 'Chad' },
          { title: 'Chile', value: 'Chile' },
          { title: 'Colombia', value: 'Colombia' },
          { title: 'Comoros', value: 'Comoros' },
          { title: 'Congo', value: 'Congo' },
          { title: 'Congo (Democratic Republic)', value: 'Congo (Democratic Republic)' },
          { title: 'Costa Rica', value: 'Costa Rica' },
          { title: 'Côte d\'Ivoire', value: 'Côte d\'Ivoire' },
          { title: 'Croatia', value: 'Croatia' },
          { title: 'Cuba', value: 'Cuba' },
          { title: 'Cyprus', value: 'Cyprus' },
          { title: 'Czech Republic', value: 'Czech Republic' },
          { title: 'Denmark', value: 'Denmark' },
          { title: 'Djibouti', value: 'Djibouti' },
          { title: 'Dominica', value: 'Dominica' },
          { title: 'Dominican Republic', value: 'Dominican Republic' },
          { title: 'Ecuador', value: 'Ecuador' },
          { title: 'Egypt', value: 'Egypt' },
          { title: 'El Salvador', value: 'El Salvador' },
          { title: 'Equatorial Guinea', value: 'Equatorial Guinea' },
          { title: 'Eritrea', value: 'Eritrea' },
          { title: 'Estonia', value: 'Estonia' },
          { title: 'Eswatini', value: 'Eswatini' },
          { title: 'Ethiopia', value: 'Ethiopia' },
          { title: 'Fiji', value: 'Fiji' },
          { title: 'Finland', value: 'Finland' },
          { title: 'Gabon', value: 'Gabon' },
          { title: 'Gambia', value: 'Gambia' },
          { title: 'Georgia', value: 'Georgia' },
          { title: 'Ghana', value: 'Ghana' },
          { title: 'Greece', value: 'Greece' },
          { title: 'Grenada', value: 'Grenada' },
          { title: 'Guatemala', value: 'Guatemala' },
          { title: 'Guinea', value: 'Guinea' },
          { title: 'Guinea-Bissau', value: 'Guinea-Bissau' },
          { title: 'Guyana', value: 'Guyana' },
          { title: 'Haiti', value: 'Haiti' },
          { title: 'Honduras', value: 'Honduras' },
          { title: 'Hungary', value: 'Hungary' },
          { title: 'Iceland', value: 'Iceland' },
          { title: 'Indonesia', value: 'Indonesia' },
          { title: 'Iran', value: 'Iran' },
          { title: 'Iraq', value: 'Iraq' },
          { title: 'Ireland', value: 'Ireland' },
          { title: 'Israel', value: 'Israel' },
          { title: 'Italy', value: 'Italy' },
          { title: 'Jamaica', value: 'Jamaica' },
          { title: 'Jordan', value: 'Jordan' },
          { title: 'Kazakhstan', value: 'Kazakhstan' },
          { title: 'Kenya', value: 'Kenya' },
          { title: 'Kiribati', value: 'Kiribati' },
          { title: 'North Korea', value: 'North Korea' },
          { title: 'South Korea', value: 'South Korea' },
          { title: 'Kuwait', value: 'Kuwait' },
          { title: 'Kyrgyzstan', value: 'Kyrgyzstan' },
          { title: 'Laos', value: 'Laos' },
          { title: 'Latvia', value: 'Latvia' },
          { title: 'Lebanon', value: 'Lebanon' },
          { title: 'Lesotho', value: 'Lesotho' },
          { title: 'Liberia', value: 'Liberia' },
          { title: 'Libya', value: 'Libya' },
          { title: 'Liechtenstein', value: 'Liechtenstein' },
          { title: 'Lithuania', value: 'Lithuania' },
          { title: 'Luxembourg', value: 'Luxembourg' },
          { title: 'Madagascar', value: 'Madagascar' },
          { title: 'Malawi', value: 'Malawi' },
          { title: 'Malaysia', value: 'Malaysia' },
          { title: 'Maldives', value: 'Maldives' },
          { title: 'Mali', value: 'Mali' },
          { title: 'Malta', value: 'Malta' },
          { title: 'Marshall Islands', value: 'Marshall Islands' },
          { title: 'Mauritania', value: 'Mauritania' },
          { title: 'Mauritius', value: 'Mauritius' },
          { title: 'Mexico', value: 'Mexico' },
          { title: 'Micronesia', value: 'Micronesia' },
          { title: 'Moldova', value: 'Moldova' },
          { title: 'Monaco', value: 'Monaco' },
          { title: 'Mongolia', value: 'Mongolia' },
          { title: 'Montenegro', value: 'Montenegro' },
          { title: 'Morocco', value: 'Morocco' },
          { title: 'Mozambique', value: 'Mozambique' },
          { title: 'Myanmar', value: 'Myanmar' },
          { title: 'Namibia', value: 'Namibia' },
          { title: 'Nauru', value: 'Nauru' },
          { title: 'Nepal', value: 'Nepal' },
          { title: 'Netherlands', value: 'Netherlands' },
          { title: 'New Zealand', value: 'New Zealand' },
          { title: 'Nicaragua', value: 'Nicaragua' },
          { title: 'Niger', value: 'Niger' },
          { title: 'Nigeria', value: 'Nigeria' },
          { title: 'North Macedonia', value: 'North Macedonia' },
          { title: 'Norway', value: 'Norway' },
          { title: 'Oman', value: 'Oman' },
          { title: 'Pakistan', value: 'Pakistan' },
          { title: 'Palau', value: 'Palau' },
          { title: 'Palestine', value: 'Palestine' },
          { title: 'Panama', value: 'Panama' },
          { title: 'Papua New Guinea', value: 'Papua New Guinea' },
          { title: 'Paraguay', value: 'Paraguay' },
          { title: 'Peru', value: 'Peru' },
          { title: 'Philippines', value: 'Philippines' },
          { title: 'Poland', value: 'Poland' },
          { title: 'Portugal', value: 'Portugal' },
          { title: 'Qatar', value: 'Qatar' },
          { title: 'Romania', value: 'Romania' },
          { title: 'Russia', value: 'Russia' },
          { title: 'Rwanda', value: 'Rwanda' },
          { title: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
          { title: 'Saint Lucia', value: 'Saint Lucia' },
          { title: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines' },
          { title: 'Samoa', value: 'Samoa' },
          { title: 'San Marino', value: 'San Marino' },
          { title: 'São Tomé and Príncipe', value: 'São Tomé and Príncipe' },
          { title: 'Saudi Arabia', value: 'Saudi Arabia' },
          { title: 'Senegal', value: 'Senegal' },
          { title: 'Serbia', value: 'Serbia' },
          { title: 'Seychelles', value: 'Seychelles' },
          { title: 'Sierra Leone', value: 'Sierra Leone' },
          { title: 'Singapore', value: 'Singapore' },
          { title: 'Slovakia', value: 'Slovakia' },
          { title: 'Slovenia', value: 'Slovenia' },
          { title: 'Solomon Islands', value: 'Solomon Islands' },
          { title: 'Somalia', value: 'Somalia' },
          { title: 'South Africa', value: 'South Africa' },
          { title: 'South Sudan', value: 'South Sudan' },
          { title: 'Spain', value: 'Spain' },
          { title: 'Sri Lanka', value: 'Sri Lanka' },
          { title: 'Sudan', value: 'Sudan' },
          { title: 'Suriname', value: 'Suriname' },
          { title: 'Sweden', value: 'Sweden' },
          { title: 'Switzerland', value: 'Switzerland' },
          { title: 'Syria', value: 'Syria' },
          { title: 'Taiwan', value: 'Taiwan' },
          { title: 'Tajikistan', value: 'Tajikistan' },
          { title: 'Tanzania', value: 'Tanzania' },
          { title: 'Thailand', value: 'Thailand' },
          { title: 'Timor-Leste', value: 'Timor-Leste' },
          { title: 'Togo', value: 'Togo' },
          { title: 'Tonga', value: 'Tonga' },
          { title: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
          { title: 'Tunisia', value: 'Tunisia' },
          { title: 'Turkey', value: 'Turkey' },
          { title: 'Turkmenistan', value: 'Turkmenistan' },
          { title: 'Tuvalu', value: 'Tuvalu' },
          { title: 'Uganda', value: 'Uganda' },
          { title: 'Ukraine', value: 'Ukraine' },
          { title: 'United Arab Emirates', value: 'United Arab Emirates' },
          { title: 'Uruguay', value: 'Uruguay' },
          { title: 'Uzbekistan', value: 'Uzbekistan' },
          { title: 'Vanuatu', value: 'Vanuatu' },
          { title: 'Vatican City', value: 'Vatican City' },
          { title: 'Venezuela', value: 'Venezuela' },
          { title: 'Vietnam', value: 'Vietnam' },
          { title: 'Yemen', value: 'Yemen' },
          { title: 'Zambia', value: 'Zambia' },
          { title: 'Zimbabwe', value: 'Zimbabwe' },
        ],
      },
    }),
    defineField({
      name: 'professionalTitle',
      title: 'Professional Title/Role',
      type: 'string',
      validation: (Rule) => Rule.max(100),
      description: 'Professional title or role (optional)',
    }),
    defineField({
      name: 'downloadTimestamp',
      title: 'Download Timestamp',
      type: 'datetime',
      validation: (Rule) => Rule.required(),
      initialValue: () => new Date().toISOString(),
      description: 'When the brochure was downloaded',
    }),
    defineField({
      name: 'ipAddress',
      title: 'IP Address',
      type: 'string',
      description: 'IP address of the downloader (optional for tracking)',
    }),
    defineField({
      name: 'userAgent',
      title: 'User Agent',
      type: 'string',
      description: 'Browser/device information (optional for analytics)',
    }),
    defineField({
      name: 'referrer',
      title: 'Referrer',
      type: 'string',
      description: 'Source page that led to the download (optional)',
    }),
  ],
  orderings: [
    {
      title: 'Download Date (Newest First)',
      name: 'downloadDateDesc',
      by: [{ field: 'downloadTimestamp', direction: 'desc' }],
    },
    {
      title: 'Name (A-Z)',
      name: 'nameAsc',
      by: [{ field: 'fullName', direction: 'asc' }],
    },
    {
      title: 'Email (A-Z)',
      name: 'emailAsc',
      by: [{ field: 'email', direction: 'asc' }],
    },
    {
      title: 'Country',
      name: 'countryAsc',
      by: [{ field: 'country', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'fullName',
      subtitle: 'email',
      country: 'country',
      downloadTimestamp: 'downloadTimestamp',
    },
    prepare({ title, subtitle, country, downloadTimestamp }) {
      const date = downloadTimestamp ? new Date(downloadTimestamp).toLocaleDateString() : '';
      return {
        title: title || 'Unknown',
        subtitle: `${subtitle} • ${country} • ${date}`,
        media: DownloadIcon,
      };
    },
  },
});

export default brochureDownload;
